[tool.poetry]
name = "swarm-memorizer"
version = "0.1.0"
description = ""
authors = ["Mengyang (John) Cha <15233508+solarapparition@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "swarm_memorizer"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
langchain = "^0.0.353"
"ruamel.yaml" = "^0.18.5"
colorama = "^0.4.6"
openai = "^1.6.1"
pyautogen = { git = "https://github.com/microsoft/autogen.git" }
llama-index = "^0.9.32"
open-interpreter = "^0.2.0"

[tool.poetry.group.dev.dependencies]
pylint = "^3.0.3"
black = "^23.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
