"""Concepts for swarm agents."""

from enum import Enum

class Concept(Enum):
    """Concepts for swarm agents."""

    MAIN_TASK = "MAIN TASK"
    MAIN_TASK_OWNER = f"{MAIN_TASK} OWNER"
    ORCHESTRATOR = "ORCHESTRATOR"
    ORCHESTRATOR_ACTIONS = f"{ORCHESTRATOR} ACTIONS"
    EXECUTOR = "EXECUTOR"
    RECENT_EVENTS_LOG = "RECENT EVENTS LOG"
    ORCHESTRATOR_INFORMATION_SECTIONS = "ORCHESTRATOR INFORMATION SECTIONS"
    SUBTASK = "SUBTASK"
    SUBTASK_STATUS = f"{SUBTASK} STATUS"
    SUBTASK_EXECUTOR = f"{SUBTASK} {EXECUTOR}"
    FOCUSED_SUBTASK = f"FOCUSED {SUBTASK}"
    FOCUSED_SUBTASK_DISCUSSION_LOG = f"{FOCUSED_SUBTASK} DISCUSSION LOG"
    MAIN_TASK_DESCRIPTION = f"{MAIN_TASK} DESCRIPTION"
    MAIN_TASK_INFORMATION = f"{MAIN_TASK} INFORMATION"
    MAIN_TASK_DEFINITION_OF_DONE = f"{MAIN_TASK} DEFINITION OF DONE"
    TASK_MESSAGES = "TASK MESSAGES"
    LAST_READ_MAIN_TASK_OWNER_MESSAGE = f"LAST READ {MAIN_TASK_OWNER} MESSAGE"
    OBJECTIVE_POV = "OBJECTIVE POV"
    ARTIFACT = "ARTIFACT"
    CONTEXT = "CONTEXT"
    DELEGATOR = "DELEGATOR"
    DELEGATOR_INFORMATION_SECTIONS = "DELEGATOR INFORMATION SECTIONS"
